# **Text Representation**
Text representation in Natural Language Processing (NLP) is the process of converting raw text into numerical formats that computers and machine learning algorithms can process. This is critical because models operate on mathematical vectors rather than characters or words.

- It is also called as `Text Vectorization`/`Feature Extraction`

#  **1. One-Hot Encoding (OHE)**

### 🔹 What is One-Hot Encoding?
One-Hot Encoding (OHE) is a **text representation technique** that converts **categorical text data** into **numerical vectors** so that machine learning models can understand it.

Each **unique word/token** is represented as a vector of **0s and 1s**:
- `1` → token is present  
- `0` → token is absent  

📌 **Important**: OHE does **not** capture meaning or context, it only captures **presence or absence**.

---

### 🔹 How OHE Converts Text into Vectors

Assume we have the following sentences:

```text
"I love AI"
"I love ML"


### **Step 1: Create Vocabulary**

In [31]:
Vocabulary = ["I", "love", "AI", "ML"]

### **Step 2: Assign Index to Each Word**
| Word | Index |
| ---- | ----- |
| I    | 0     |
| love | 1     |
| AI   | 2     |
| ML   | 3     |


### **Step 3: Convert Sentences into Vectors**
| Sentence  | Vector       |
| --------- | ------------ |
| I love AI | [1, 1, 1, 0] |
| I love ML | [1, 1, 0, 1] |

    Each sentence is now a binary vector.

### **One-Hot Encoding Using Scikit Learn**

In [32]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Sample text data
data = [["I"], ["love"], ["AI"], ["love"], ["ML"]]

# Initialize encoder
encoder = OneHotEncoder(sparse_output=False)

# Fit and transform
encoded = encoder.fit_transform(data)

# Output
print("Vocabulary:", encoder.categories_)
print("Encoded Vectors:\n", encoded)


Vocabulary: [array(['AI', 'I', 'ML', 'love'], dtype=object)]
Encoded Vectors:
 [[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


### **One-Hot Encoding Using CountVectorizer**

In [33]:
from sklearn.feature_extraction.text import CountVectorizer

sentences = [
    "I love AI",
    "I love ML"
]

vectorizer = CountVectorizer(binary=True)
X = vectorizer.fit_transform(sentences)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("Vectors:\n", X.toarray())

Vocabulary: ['ai' 'love' 'ml']
Vectors:
 [[1 1 0]
 [0 1 1]]


### **✅ Advantages & ❌ Disadvantages of OHE**
| Advantages                        | Disadvantages                         |
| --------------------------------- | ------------------------------------- |
| Simple and easy to understand     | Creates very high-dimensional vectors |
| No mathematical assumptions       | No semantic meaning captured          |
| Works well for small vocabularies | Memory inefficient                    |
| Prevents ordinal bias             | Not suitable for large text corpora   |
| Model-friendly for basic ML       | Cannot handle unseen words well       |


📌 Best Used When:

- Vocabulary is small

- Dataset is not very large

- Baseline or educational models

📌 Avoid When:

- Large text data

- Semantic understanding is required

# **2. Bag of Words (BoW)**

### 🔹 **What is Bag of Words?**
Bag of Words (BoW) is a **text representation technique** that converts text into **numerical vectors** based on **word frequency**.

📌 BoW only cares about:
- **Which words appear**
- **How many times they appear**

🚫 It **ignores grammar, word order, and context**.

---

### 🔹 **How BoW Converts Text into Vectors (Simple Explanation)**
Consider these sentences:

```text
"I love AI"
"I love ML"


### **Step 1: Create Vocabulary**

In [34]:
Vocabulary = ["I", "love", "AI", "ML"]

### **Step 2: Count Word Occurrences**
| Sentence  | I | love | AI | ML |
| --------- | - | ---- | -- | -- |
| I love AI | 1 | 1    | 1  | 0  |
| I love ML | 1 | 1    | 0  | 1  |

    Each sentence is represented as a count-based vector.

In [35]:
from sklearn.feature_extraction.text import CountVectorizer

sentences = [
    "I love AI",
    "I love ML"
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(sentences)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("Vectors:\n", X.toarray())


Vocabulary: ['ai' 'love' 'ml']
Vectors:
 [[1 1 0]
 [0 1 1]]


# **3. BoW with N-grams (Unigrams + Bigrams)**

In [36]:
# Bigram
from sklearn.feature_extraction.text import CountVectorizer

sentences = [
    "I love AI",
    "I love ML"
]

vectorizer = CountVectorizer(ngram_range=(1, 2))
X = vectorizer.fit_transform(sentences)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("Vectors:\n", X.toarray())


Vocabulary: ['ai' 'love' 'love ai' 'love ml' 'ml']
Vectors:
 [[1 1 1 0 0]
 [0 1 0 1 1]]


In [37]:
vectorizer.vocabulary_

{'love': 1, 'ai': 0, 'love ai': 2, 'ml': 4, 'love ml': 3}

In [38]:
# Trigram
from sklearn.feature_extraction.text import CountVectorizer

sentences = [
    "I love AI",
    "I love ML"
]

vectorizer = CountVectorizer(ngram_range=(1, 3))
X = vectorizer.fit_transform(sentences)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("Vectors:\n", X.toarray())

Vocabulary: ['ai' 'love' 'love ai' 'love ml' 'ml']
Vectors:
 [[1 1 1 0 0]
 [0 1 0 1 1]]


In [39]:
vectorizer.vocabulary_

{'love': 1, 'ai': 0, 'love ai': 2, 'ml': 4, 'love ml': 3}

## **BoW vs One-Hot Encoding**
| Feature                | OHE  | BoW        |
| ---------------------- | ---- | ---------- |
| Uses frequency         | ❌ No | ✅ Yes      |
| Vector sparsity        | High | High       |
| Captures importance    | ❌ No | ⚠️ Partial |
| Handles repeated words | ❌ No | ✅ Yes      |

--------------------------------------------------------

## **✅ Advantages & ❌ Disadvantages of BoW**
| Advantages                         | Disadvantages                   |
| ---------------------------------- | ------------------------------- |
| Simple and fast                    | Ignores word order              |
| Captures word frequency            | No semantic meaning             |
| Easy to implement                  | High-dimensional sparse vectors |
| Works well for text classification | Sensitive to vocabulary size    |
| Can use n-grams                    | Fails on unseen words           |


📌 Best Used When:

- Text classification tasks

- Small to medium datasets

- Baseline ML models (Naive Bayes, Logistic Regression)

📌 Avoid When:

- Context and meaning are important

- Large-scale NLP tasks

# **4. TF-IDF (Term Frequency – Inverse Document Frequency)**

## 🔹 **What is TF-IDF?**
TF-IDF is a **statistical text representation technique** that measures how **important a word is to a document** relative to a collection of documents (corpus).

📌 Unlike BoW, TF-IDF:
- Reduces the importance of **common words**
- Increases the importance of **rare but meaningful words**

---

## 🔹 **How TF-IDF Works**

TF-IDF is a product of **two components**:

### **1️⃣ Term Frequency (TF)**
Measures how often a word appears in a document.

```text
TF(word) = (Number of times word appears in a document) 
           --------------------------------------------
           (Total number of words in the document)


### 2️⃣ Inverse Document Frequency (IDF)

Measures how unique a word is across all documents.

IDF(word) = log(`Total number of documents` / `Number of documents containing the word`)



### **Final Formula**

TF-IDF(word) = TF(word) × IDF(word)

### Example (Intuition)

Documents:

    D1: "I love AI"
    D2: "I love ML"

- Word "love" → appears in every document → low IDF

- Word "AI" → appears in only one document → high IDF

📌 TF-IDF assigns higher weight to "AI" and "ML" than to "love".

### **TF-IDF using TfidfVectorizer**

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer

sentences = [
    "I love AI",
    "I love ML"
]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(sentences)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("TF-IDF Vectors:\n", X.toarray())


Vocabulary: ['ai' 'love' 'ml']
TF-IDF Vectors:
 [[0.81480247 0.57973867 0.        ]
 [0.         0.57973867 0.81480247]]


### **TF-IDF with N-grams**

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

sentences = [
    "I love AI",
    "I love ML"
]

vectorizer = TfidfVectorizer(ngram_range=(1, 2))
X = vectorizer.fit_transform(sentences)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("TF-IDF Vectors:\n", X.toarray())


Vocabulary: ['ai' 'love' 'love ai' 'love ml' 'ml']
TF-IDF Vectors:
 [[0.6316672  0.44943642 0.6316672  0.         0.        ]
 [0.         0.44943642 0.         0.6316672  0.6316672 ]]


### **BoW vs TF-IDF**
| Feature                | BoW   | TF-IDF   |
| ---------------------- | ----- | -------- |
| Uses frequency         | ✅ Yes | ✅ Yes    |
| Penalizes common words | ❌ No  | ✅ Yes    |
| Captures importance    | ❌ No  | ✅ Better |
| Semantic meaning       | ❌ No  | ❌ No     |

### **✅ Advantages & ❌ Disadvantages of TF-IDF**
| Advantages                         | Disadvantages                   |
| ---------------------------------- | ------------------------------- |
| Highlights important words         | Still ignores word order        |
| Reduces effect of stopwords        | No semantic understanding       |
| Works well for text classification | High-dimensional sparse vectors |
| Better than BoW                    | Struggles with synonyms         |
| Fast and scalable                  | Not suitable for deep learning  |

📌 Best Used When:

- Text classification

- Search engines

- Keyword extraction

- Medium-sized NLP problems

📌 Avoid When:

- Context and word relationships matter

- Deep semantic understanding is required


# **5. Assignment**

## **5.1 Pre-Processing**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./data/IMDB Dataset.csv')
df.head()

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


In [3]:
# remove html tags
import re
def remove_html_tags(text):

    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [5]:
df['review'] = df['review'].apply(remove_html_tags)
df['review'][1]

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [7]:
# lowercase
df['review'] = df['review'].str.lower()
df['review'][1]

'a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well done.'

In [8]:
import string
exclude = string.punctuation
# remove punctuation
def remove_punc(text):
    return text.translate(str.maketrans("","",exclude))

In [ ]:
df['review'] = df['review'].apply(remove_punc)

'a wonderful little production the filming technique is very unassuming very oldtimebbc fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece the actors are extremely well chosen michael sheen not only has got all the polari but he has all the voices down pat too you can truly see the seamless editing guided by the references to williams diary entries not only is it well worth the watching but it is a terrificly written and performed piece a masterful production about one of the great masters of comedy and his life the realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream techniques remains solid then disappears it plays on our knowledge and our senses particularly with the scenes concerning orton and halliwell and the sets particularly of their flat with halliwells murals decorating every surface are terribly well done'

In [ ]:
df['review'][5]